### ISSUE TITLE
msg log - error without time stamp

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#136]
Error msg from the message logger appears with out time stamp:

[ERR] pipeline.DemonLAST try error: Intermediate dot '.' indexing produced a comma-separated list with 24 values, but it must produce a single value when followed by subsequent indexing operations. / funname: singleRaw2proc @ line: 361
[ERR] Exception: id=MATLAB:index:expected_one_output_from_intermediate_indexing msg=Intermediate dot '.' indexing produced a comma-separated list with 24 values, but it must produce a single value when followed by subsequent indexing operations.
[ERR] stack: Ind=1; FunName=singleRaw2proc; line=361
[ERR] stack: Ind=2; FunName=multiRaw2procCoadd; line=391
[ERR] stack: Ind=3; FunName=DemonLAST.main; line=1318
[ERR] pipeline.DemonLAST: 20 images moved to failed directory
09:01:09.234 [INF] pipeline.DemonLAST / pipeline.generic.multiRaw2procCoadd analyzed 20 images starting at 20230425.212504.975
09:01:09.237 [INF] pipeline.DemonLAST / pipeline.generic.multiRaw2procCoadd run time [s]: 233030.4
09:01:09.290 [INF] pipline.DemonLAST executing pipeline for group 7 - First image: /raid/eran/projects/telescopes/LAST/Images_PipeTest/testPipe/LAST.01.02.02/new/LAST.01.02.01_20230425.212444.974_clear_185-02_060_001_001_sci_raw_Image_1.fits
09:01:09.293 [INF] pipeline.DemonLAST / pipeline.generic.multiRaw2procCoadd run time [s]: 233030.4

**Comment by elhadan** [comment]
I have found the origin of this and have a fix but will discuss with Chen about it as I need to understand why this was written in this way before pushing.
Note that the missing timestamp is also for: Fatal, Assert and Warnings.

MsgLogger.msgLog() - line 197:
Any log messeges like the above types (which are not passed as cell), will be printed out of msgStyle instead of msgLog. We can simply add datetime to said function, but it might be better to merge the code of both functions.

**Comment by EranOfek** [comment]
close after fixing.
