### ISSUE TITLE
LAST target list doesn't have the right spacing between fields

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#163]
Targetlist created by: `T = celestial.Targets.generateTargetList('last')`

In below plot: recatangles mark the area observed by each camera. Dots are the Mount coordinates (i.e. from the file name). There is too much overlap in Dec direction, but too little in RA direction. The telescope pointing seems roughly ok (= the dot is close to the center of observed FoV).

![lass_area](https://github.com/EranOfek/AstroPack/assets/14293969/fd8135ab-758a-49f3-b346-b6a93258650c)

Note: For M3 and M10 telescope alignment and pointing model were finished. I improved alignment and pointing model for M2 later (telescopes were too far apart) and updated the pointing model for M8.

**Comment by EranOfek** [comment]
1. Can you produce a plot of offset between mount coordinates M_JRA, M_JDEC and the astrometric coordinate of the pointing center, defined as the mean of the centers of the 4 telescopes.
2. The problem was in the default argument of :
celestial.Targets.generateTargetList('last')
They were adjusted such that the long axis of the field is in RA direction, while in our case it is in the dec direction.
Therefore, I changed the default arguments to [85, 28]
This means that we will have to retake the all-sky survey.
