### ISSUE TITLE
bad path and file name for some processed images

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#195]
When running the pipeline on last04w for telescope 4:

`D.main('StartJD',[2460068.2477], 'EndJD',[2460068.3179],'StopWhenDone',true,'SaveEpochProduct',{'Image','Mask','Cat','PSF'});
`

It fails for the first 2 groups because the visit products can't be saved. See: https://github.com/EranOfek/AstroPack/issues/194

For the 3rd group it fails as:

```
07:58:48.651 [INF] pipline.DemonLAST executing pipeline for group 3 - First image: /last04w/data2/archive/LAST.01.04.04/new/LAST.01.04.04_20230503.191744.921_clear_168+56_040_001_001_sci_raw_Image_1.fits
07:58:48.655 [INF] pipeline.DemonLAST / pipeline.generic.multiRaw2procCoadd run time [s]:  355.1
08:04:12.901 [INF] pipline.DemonLAST finish executing pipeline - start saving data
08:04:12.933 [INF] pipeline.DemonLAST / pipeline.generic.multiRaw2procCoadd run time [s]:  355.1
08:04:43.618 [INF] FileName=/last04w/data2/archive/LAST.01.04.04//-4712/01/NaN/proc/3/LAST.01.04.04_NaN_clear_168+56__001__sci_coadd_Image_1.fits, DataProperty=Image, image is empty - not saved
08:04:43.623 [INF] FileName=/last04w/data2/archive/LAST.01.04.04//-4712/01/NaN/proc/3/LAST.01.04.04_NaN_clear_168+56__001__sci_coadd_Mask_1.fits, DataProperty=Mask, image is empty - not saved
08:04:43.627 [INF] FileName=/last04w/data2/archive/LAST.01.04.04//-4712/01/NaN/proc/3/LAST.01.04.04_NaN_clear_168+56__001__sci_coadd_Cat_1.fits, DataProperty=Cat, image is empty - not saved
08:04:43.632 [INF] FileName=/last04w/data2/archive/LAST.01.04.04//-4712/01/NaN/proc/3/LAST.01.04.04_NaN_clear_168+56__001__sci_coadd_PSF_1.fits, DataProperty=PSF, image is empty - not saved
08:04:44.258 [INF] FileName=/last04w/data2/archive/LAST.01.04.04//-4712/01/NaN/proc/3/LAST.01.04.04_NaN_clear_168+56_000_001_001_sci_merged_Cat_1.fits, DataProperty=CatData, image is empty - not saved
08:04:46.706 [INF] FileName=/last04w/data2/archive/LAST.01.04.04//-4712/01/NaN/proc/3/LAST.01.04.04_NaN_clear_168+56_000_001_001_sci_merged_MergedMat_1.hdf5, DataProperty=MergedMat, image is empty - not saved
08:04:55.056 [INF] last_operational: Connecting to server 10.23.1.25:5432, database: last_operational, user: postgres/postgres
08:04:55.188 [INF] DbConnection: open
08:04:55.215 [INF] DbDriver: loadDriver
08:04:56.196 [INF] DbConnection: open: Url: jdbc:postgresql://10.23.1.25:5432/last_operational
08:04:56.466 [INF] DbConnection: open: connect OK: jdbc:postgresql://10.23.1.25:5432/last_operational
08:04:56.494 [INF] DbConnection: open done
08:04:56.545 [INF] last_operational: Connected, Postgres version: PostgreSQL 14.4 (Ubuntu 14.4-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
08:04:56.635 [INF] last_operational: The DB contains the following public tables:
08:04:56.642 [INF] last_operational: test_proc_src_catalog raw_images proc_images coadd_images test_coadd_src_catalog proc_src_catalog coadd_src_catalog test_raw_images test_coadd_images test_proc_images 

08:04:57.753 [INF] last_operational: Processed: 20 entries
08:04:57.763 [INF] last_operational: Table raw_images successfully populated with img metadata
08:04:57.774 [INF] Insert images to LAST raw images table - success: 1
08:04:57.778 [INF] pipeline.DemonLAST / pipeline.generic.multiRaw2procCoadd run time [s]:  355.1
08:05:12.385 [INF] last_operational: Processed: 480 entries
08:05:12.389 [INF] last_operational: Table proc_images successfully populated with img metadata
08:05:12.397 [INF] Insert images to LAST proc images table - success: 1
08:05:12.401 [INF] pipeline.DemonLAST / pipeline.generic.multiRaw2procCoadd run time [s]:  355.1
[ERR] pipeline.DemonLAST try error: Cannot open the specified file. / funname: xxhash @ line: 27
[ERR] Exception: id=MATLAB:mexFunction:cannotOpenFile msg=Cannot open the specified file.
[ERR] stack: Ind=1; FunName=xxhash; line=27
[ERR] stack: Ind=2; FunName=AstroDb.insert; line=678
[ERR] stack: Ind=3; FunName=DemonLAST.main; line=1657
Error using movefile
Unknown error occurred.

Error in io.files.moveFiles (line 94)
        movefile(Source, Destination{Ifile});

Error in pipeline.DemonLAST/main (line 1751)
                            io.files.moveFiles(RawImageList,
                            FN_Sci_Groups(Igroup).genFull('FullPath',FailedPath)); 
```

The pathes or D all look ok:
```
>> D

D = 

  DemonLAST with properties:

             CI: [1×1 CalibImages]
    ProjectName: 'LAST'
           Node: 1
        DataDir: 2
      CamNumber: []
       BasePath: '/last04w/data2/archive/LAST.01.04.04'
        NewPath: '/last04w/data2/archive/LAST.01.04.04/new'
      CalibPath: '/last04w/data2/archive/LAST.01.04.04/calib'
     FailedPath: '/last04w/data2/archive/LAST.01.04.04/failed'
        LogPath: '/last04w/data2/archive/LAST.01.04.04/log'
        RefPath: '/last04w/data/reference'
         ObsCoo: [35 30 415]
           Name: []
       DataType: [0×0 AstroDataType]
         Config: [1×1 Configuration]
         Logger: [1×1 MsgLogger]
       UserData: []

```

Indeed it saves processed images under:
```
ocs@last04w:/last04w/data2/archive/LAST.01.04.04$ ls -l ./-4712/01/NaN/proc/
total 84
drwxrwxr-x 2 ocs ocs 24576 Jul 16 13:22 1
drwxrwxr-x 2 ocs ocs 20480 Jul 18 07:58 2
drwxrwxr-x 2 ocs ocs 40960 Jul 18 08:04 3
```

While the raw images are moved to the correct directory:
`ls 2023/05/03/raw/*`

All 20 images can be opened with ds9 and JD and RA and Dec have valid entries.

You can find them at:
```
ocs@last04w:/last04w/data2/archive/LAST.01.04.04$ ls 2023/05/03/raw/
LAST.01.04.04_20230503.191124.796_clear_168+56_021_001_001_sci_raw_Image_1.fits
LAST.01.04.04_20230503.191144.812_clear_168+56_022_001_001_sci_raw_Image_1.fits
LAST.01.04.04_20230503.191204.806_clear_168+56_023_001_001_sci_raw_Image_1.fits
LAST.01.04.04_20230503.191224.828_clear_168+56_024_001_001_sci_raw_Image_1.fits
LAST.01.04.04_20230503.191244.844_clear_168+56_025_001_001_sci_raw_Image_1.fits
LAST.01.04.04_20230503.191304.829_clear_168+56_026_001_001_sci_raw_Image_1.fits
LAST.01.04.04_20230503.191324.836_clear_168+56_027_001_001_sci_raw_Image_1.fits
LAST.01.04.04_20230503.191344.852_clear_168+56_028_001_001_sci_raw_Image_1.fits
LAST.01.04.04_20230503.191404.855_clear_168+56_029_001_001_sci_raw_Image_1.fits
LAST.01.04.04_20230503.191424.852_clear_168+56_030_001_001_sci_raw_Image_1.fits
LAST.01.04.04_20230503.191444.857_clear_168+56_031_001_001_sci_raw_Image_1.fits
LAST.01.04.04_20230503.191504.862_clear_168+56_032_001_001_sci_raw_Image_1.fits
LAST.01.04.04_20230503.191524.870_clear_168+56_033_001_001_sci_raw_Image_1.fits
LAST.01.04.04_20230503.191544.884_clear_168+56_034_001_001_sci_raw_Image_1.fits
LAST.01.04.04_20230503.191604.891_clear_168+56_035_001_001_sci_raw_Image_1.fits
LAST.01.04.04_20230503.191624.904_clear_168+56_036_001_001_sci_raw_Image_1.fits
LAST.01.04.04_20230503.191644.898_clear_168+56_037_001_001_sci_raw_Image_1.fits
LAST.01.04.04_20230503.191704.915_clear_168+56_038_001_001_sci_raw_Image_1.fits
LAST.01.04.04_20230503.191724.912_clear_168+56_039_001_001_sci_raw_Image_1.fits
LAST.01.04.04_20230503.191744.921_clear_168+56_040_001_001_sci_raw_Image_1.fits

```

**Comment by EranOfek** [comment]
what about the other groups? is it ok?

**Comment by EranOfek** [comment]
Nora - Please dubug this problem.
1. Is this happening all the times or only for some of the groups?
2. There are two maybe related issues - the first is the xhash (I will ask Sasha to take a look),
but the second please investigate:
Try to copy the content of the failed dir to the new dir and run again this time with a debug point before the pipeline write the products.
Check the content of the AllSI and Coadd AstroImage objects:
1. how many images/epochs?
2. Is all the images populated or three are some empty images? you can use the isEmptyImage method.

**Comment by EranOfek** [comment]
Sasha - can you please take a look (failed on xxhash) - I thought that we are not using this anymore.
Is it failing because the image is empty? or path doesn't contain image?

**Comment by agioffe** [comment]
We are using hash sums by default when we are injecting image headers with a regular procedure of db.AstroDB.insert into the DB. Only the catalog data goes without them, as we have not developed a method to get sensible hash sums with bulk injection. 
As for the error, it looks like the xxhash fails because there is not file by the name given to the function:

ocs@last04w:/last04w/data2/archive/LAST.01.04.04/-4712/01/NaN/proc/3$ ls LAST.01.04.04_NaN_clear_168+56__001__sci_coadd_Image_1.fits
ls: cannot access 'LAST.01.04.04_NaN_clear_168+56__001__sci_coadd_Image_1.fits': No such file or directory
ocs@last04w:/last04w/data2/archive/LAST.01.04.04/-4712/01/NaN/proc/3$ ls LAST.01.04.04_*clear_168+56*001*sci_coadd_Image_1.fits |wc
     46      46    3772
ocs@last04w:/last04w/data2/archive/LAST.01.04.04/-4712/01/NaN/proc/3$ ls LAST.01.04.04_*clear_168+56*001*sci_coadd_Image_1.fits |head -n 3
LAST.01.04.04_20230503.191444.855_clear_168+56_001_001_002_sci_coadd_Image_1.fits
LAST.01.04.04_20230503.191444.855_clear_168+56_001_001_003_sci_coadd_Image_1.fits
LAST.01.04.04_20230503.191444.855_clear_168+56_001_001_004_sci_coadd_Image_1.fits
ocs@last04w:/last04w/data2/archive/LAST.01.04.04/-4712/01/NaN/proc/3$ 

or directly:

> File = '/last04w/data2/archive/LAST.01.04.04/-4712/01/NaN/proc/3/LAST.01.04.04_NaN_clear_168+56__001__sci_coadd_Image_1.fits'

File =

    '/last04w/data2/archive/LAST.01.04.04/-4712/01/NaN/proc/3/LAST.01.04.04_NaN_clear_168+56__001__sci_coadd_Image_1.fits'

>> tools.checksum.xxhash('FileName',File)
Error using mex_xxhashFile
Cannot open the specified file.

Error in tools.checksum.xxhash (line 27)
        Result = tools.checksum.mex.mex_xxhashFile(Args.FileName, int64(Args.Seed));
 
>> 

I suppose that when the filename issue is solved, there will be no problems with the hash.

**Comment by EranOfek** [comment]
I suspect the inage does not exist.
Before you add an image to the db you should check if the image data exist
(isEmptyImage method).
You should have an argument that specifying if the prigram will insert a
record only if the images is not empty.
Please verify that this solves the problem.

**Comment by agioffe** [comment]
This part of the code attempts to inject a matrix of AHs (and add the hash of the corresponding filenames as one of the columns), which are contained within the AllSI and Coadd AI objects. In fact, the hash function itself does not care about AHs or images, it works just with the disk files and does not care what is inside the file. 

Do you indeed think that at this step it is reasonable to check if there are images in each element of the AllSI and Coadd AI objects?

**Comment by EranOfek** [comment]
I understand, but not sure this is relevant for our problem.
I suspect that the file name not exist (in fact it is illegal) because the
image doesn't exist and was not written to disk.
Only images which exist should be added to DB:
to do so you can, for example:

FlagExist = ~AllSI.isEmptyImage;
and than write DB only for: AllSI(FlagExist)
and similarly for Coadd.
Before you implement this, just verify that this is indeed the problem.

**Comment by agioffe** [comment]
Looks like it is not the problem with AllSI, but indeed 1 of the 24 Coadd AI's does not contain an image (see below).
I will implement the check, but do not we want to see the error at the earliest possible occasion instead of closing eyes on it?
One technical issue: do I take it right that currently I do not change anything on the last nodes, but rather make changes on a local machine, push them and then they will be pulled at last nodes during the next (sub)release?

K>> FlagExist = ~AllSI.isemptyImage;
K>> FlagExist

FlagExist =

  20×24 logical array

   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1

K>> 
K>> FlagExist = ~Coadd.isemptyImage;
K>> FlagExist

FlagExist =

  24×1 logical array

   0
   1
   1
   1
   1
   1
   1
   1
   1
   1
   1
   1
   1
   1
   1
   1
   1
   1
   1
   1
   1
   1
   1
   1

K>> Coadd(1)

ans = 

  AstroImage with properties:

           Image: []
            Back: []
             Var: []
            Mask: []
             Exp: []
          Header: {0×3 cell}
             Key: [1×1 struct]
             PSF: []
           Table: [0×0 table]
       ImageData: [1×1 SciImage]
        BackData: [1×1 BackImage]
         VarData: [1×1 VarImage]
        MaskData: [1×1 MaskImage]
         ExpData: [1×1 ExpImage]
      HeaderData: [1×1 AstroHeader]
         CatData: [1×1 AstroCatalog]
         PSFData: [1×1 AstroPSF]
             WCS: [1×1 AstroWCS]
    PropagateErr: 0
            Name: []
        DataType: [0×0 AstroDataType]
          Config: [1×1 Configuration]
          Logger: [1×1 MsgLogger]
        UserData: []

**Comment by EranOfek** [comment]
Hi Sasha, Is the bug fixed? If so close the issue.

**Comment by agioffe** [comment]
Yes, now now AIs without images produce records in the DB, however what prevented the images from being produced normally is still unclear.
