### ISSUE TITLE
`imProc.image.image2subimages()` doesn't set `CROPID` in the header

### ISSUE THREAD

**Issue by EastEriq** [EranOfek/AstroPack#210]
and thus creates a loophole for `imProc.io.writeProduct`, see issue #209

**Comment by EranOfek** [comment]
imProc.image.image2subimagfes, now by default, add a CROPID keyword to the header indicating the index of the sub image.
See the 'KeyCropID' argument.

also, in line 419 in pipeline.generic.singleRaw2proc - removed the code that add the CROPID key, because it is not done by image2subimages...

Please test.

**Comment by EranOfek** [comment]
sorry - my fault - try again.

**Comment by EranOfek** [comment]
please put a breakpoint in line 137 in image2subimages:
1. Is the code reach this point?
2. If yes - check the content of Result.HeaderData...

**Comment by EastEriq** [comment]
CROPID is now in the header without explicitly setting it, so this can be considered closed, probably by commit 131a075b62.
