### ISSUE TITLE
MaskImage.bitwise_cutouts - MEX version is needed

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#211]
MaskImage.bitwise_cutouts - MEX version is needed

New fun name: imUtil.cut.bitwise_cutouts
Input:
   2D array (uint16, uint32)
   Vector of X coordinates (double)
   Vector of Y coordinates (double)
   HalfSize - half size of cutouts (stamps) around X, Y positions. Stamp size will be 1+2*HalfSize
   Logical indicating if to use "or" (true) or "and" (false)

Output : Vector whose length is the same as the X (or Y) vectors, abd contains uint16 or uint32

The function will cut stamps around the X, Y positions (use imUtil.cut.mex.mex_cutout)
and for each stamp will use tools.array.bitor_array or tools.array.bitand_array
over all pixels in each stamp.

**Comment by elhadan** [comment]
I have added the new function and the compiled win versions.
I have used the mex_cutout function to help with some of the bugs.
The function currently calculates bitwise by itself, as the tools.array mex versions iterate on the pixels, it is more efficient to just iterate on them in this function instead of creating and sending matrices. 

Example:
Array32 = uint32(randi(2^32-1,100,100,1));
res=imUtil.cut.mex.mex_bitwise_cutouts_int32(Array32,[23 34 76 12 76],[32 65 87 34 54],1,true)

**Comment by EranOfek** [comment]
Excellent.
Can you compare run time to old version.
For testing use 1700 by 1700 32bit image with 1000 random positions

**Comment by elhadan** [comment]
I have added a test file mex_bitwise_cutouts_unitTest.m.
I am not sure what is the old version - as there is no one function that exactly does the same, so I tested the following:
The new bitwise function compared to the Chen's mex function that creates the stamps cube. It takes almost the same time (the bitwise function takes around 96% of the cutouts function), without doing the bitwise. Of course, adding the bitwise operation will only make this better.

Notes:
1. I used unit16 as the mex_cutouts cube code does not accept uint32.
2. The current bitwise code does not handle stamps which are out of bounds - we need to define what we want the code to do for those cases.

**Comment by EranOfek** [comment]
1. The code need to work with uint32 and uint16.
2. unitTest is for the entire package and it name must be unitTest.m no
other variations.
3. As i told you - for outof bounds you should pad with all bit false or
true, for and and or, respectively.

**Comment by elhadan** [comment]
1. The new code works with uint32. The old cube cutouts code does not accept uint32, so the runtime was only compared to the unit16. I have edited the unitTest to test both versions regardless. 

2. I have moved the testing to package (+imUtil) unitTest, and deleted the wrong unitTest file. It seems after a few changes the code runs faster (unitTest output from my machine):
Bitwise cutouts (bitwise_or: 1) uint16 avg time: 4.636432e-04, old cutouts avg time: 3.051413e-03, ratio: 15.19% 
Bitwise cutouts (bitwise_or: 1) uint32 avg time: 3.853606e-04 
Bitwise cutouts (bitwise_or: 0) uint16 avg time: 9.206837e-04, old cutouts avg time: 6.188531e-03, ratio: 14.88% 
Bitwise cutouts (bitwise_or: 0) uint32 avg time: 7.549772e-04 

3. I have added code to deal with outofbounds. I think that the padding is the other way around? If we pad with false for and, we will always get false as a result? 
If I understood correctly, and we want the outofbounds pixels to not "change" the result - I think it will be more efficient to not pad, but just only cut and calculate the bitwise operation on the pixels that are in bound (i.e., if we start from position 1,1, and want a 10 pixels half size stamp, the stamp will be 1:11,1:11).
This is the way I implemented the fix, so if I misunderstood - tell me.

**Comment by EranOfek** [comment]
the unitTest should be in imUtil.cut, not in imUtil.

yes - not padding will be more efficient.

**Comment by elhadan** [comment]
Moved to correct unitTest.m.

**Comment by EranOfek** [comment]
1. Excessive number of simulations - changed to 1.
2. No need to write operations in unitTest to log file - commented.

**Comment by EranOfek** [comment]
Added an imUtil.cut.bitwise_cutouts function wrapper.

**Comment by EranOfek** [comment]
The new function is about 5 times faster than MaskImage/bitwise_cutouts

However, I encountered a case in which the output was not identical:

```
Im=uint32(rand(1700,1700).*2.^32);
IC=MaskImage({Im});
X=rand(1000,1).*1700;
Y=rand(1000,1).*1700;
tic;R=IC.bitwise_cutouts([X,Y],'or','HalfSize',2);toc
tic;R1=imUtil.cut.bitwise_cutouts(Im,X,Y,2);toc      
find(R1~=R)
```

Need to investigate, and debug manually.

**Comment by EranOfek** [comment]
after careful debuging need to replace the function for the pipeline (in MaksImage).

**Comment by EranOfek** [comment]
BUG:
```
R1=imUtil.cut.bitwise_cutouts(uint32(Im),1,-5,2)
```

when stamp is completly outside the image the result should be 0.

**Comment by elhadan** [comment]
1. Fixed the out-of-bounds bug.
2. Fixed another bug I found: when checking if pixels are out of bounds, unexpected behavior sometimes happened as the ncols and nrows vars were unsigned which caused the comparison to fail.
3. I am not sure if the non-identical results you reported were caused because of one of those bugs, but I suspect that they did (as I only encountered non-identical results before fixing it). Also note, that the testing code you wrote may try to find x and y positions that are in place 0, instead of 1 (which does not exist in matlab terms). While the new cutouts code handles this, the old code does not which resulted in an error.
4. I incorpareted your test inside the unitTest (starting from position 1, not 0) and run it with 1000 iterations and didn't encounter any more non-identical results (code was pushed with 1 iteration though).

**Comment by EranOfek** [comment]
I pull and tested and it doesn't work:
```
Im=uint32(zeros(1700,1700));
Im(1,1)=2;
R1=imUtil.cut.bitwise_cutouts(uint32(Im),-11,-5,2)
% answer is 2 instead of 0
```

**Comment by elhadan** [comment]
Fixed by removing old code that changed negative position values to zeros as that is not the behavior we want (recompiled for windows and pushed).

**Comment by EranOfek** [comment]
Working - the problem was that I used the old compiled version.
The new version is about 40 times faster!
