### ISSUE TITLE
loadCalib error

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#219]
== last08w/last-messages.log.7.gz:Jul 19 00:00:05 localhost last-pipeline[823451
]: {#010Error using cd
== last08w/last-messages.log.7.gz:Jul 19 00:00:05 localhost last-pipeline[823451
]: Error in pipeline.DemonLAST/loadCalib (line 1321)
== last08w/last-messages.log.7.gz:Jul 19 00:00:05 localhost last-pipeline[823451
]: Error in pipeline.DemonLAST/main (line 1471)

need a more readable error message - or create dir?

**Comment by YarinMS** [comment]
This error is a month old. This is the same problem from issue #198 . Where I changed back the directories on all computers back to where they belong. I did it for all BUT last08w. Since I couldn't establish connection back then. 
a screen shot from #198 for reference :
<img width="592" alt="image" src="https://github.com/EranOfek/AstroPack/assets/118757319/5063e6dd-e273-4cc8-bfb1-7def48f489df">

So I've forgot to take care of last08w. And therefore the problem would repeat itself when trying to process images on last08w (A thing that didn't happen so far). Thanks for the reminder.

* side note : you can see from the screenshot that this was the case in last08e as well, changing the directories path solved this problem, we know that since I used the pipeline on last08e and other computers as well.

**Comment by EranOfek** [comment]
So is this solved now? If so please close the issue.

**Comment by YarinMS** [comment]
Solved.

**Comment by YarinMS** [comment]
Solved.
