### ISSUE TITLE
Use start time in filename of coadded products instead of mid time

### ISSUE THREAD

**Issue by noralinn** [EranOfek/AstroPack#240]
For the coadded images could we include the start time in the file name instead of the mid time of the visit?

That way the filename is deterministic and it's easier to match raw and processed data.

For example for selecting the references I have a list with raw images and which image I'd like to use. Then I cross match with a list of images that have already been processed. To make sure that I actually pick the right coadded image, I have to convert the datetime from the file name to JD and check whether they are similar within ~400s or so.
If the filename would contain the time of the first image I could simply compare the strings.

**Comment by agioffe** [comment]
I do agree with Nora that it would be better to use the start time of the stack in COADD file names. 

Here is an example when the names within 1 data set are different and this looks quite misleading and not useful for further analysis.
In the field-ordered list of COADD catalogs below 3 files have a name containing the 222955.434 time stamp, while the other 21 files have 222945.430 (also, another subset of 8 of 24 files is named *346+79_002* while the rest have *346+79_001*: is it  related to the timestamp issue?):

222635v8/LAST.01.08.03_20230616.222945.430_clear_346+79_001_001_024_sci_coadd_Cat_1.fits
222635v8/LAST.01.08.03_20230616.222945.430_clear_346+79_001_001_023_sci_coadd_Cat_1.fits
222635v8/LAST.01.08.03_20230616.222945.430_clear_346+79_001_001_022_sci_coadd_Cat_1.fits
222635v8/LAST.01.08.03_20230616.222945.430_clear_346+79_001_001_021_sci_coadd_Cat_1.fits
222635v8/LAST.01.08.03_20230616.222955.434_clear_346+79_002_001_020_sci_coadd_Cat_1.fits
222635v8/LAST.01.08.03_20230616.222945.430_clear_346+79_002_001_019_sci_coadd_Cat_1.fits
222635v8/LAST.01.08.03_20230616.222945.430_clear_346+79_002_001_018_sci_coadd_Cat_1.fits
222635v8/LAST.01.08.03_20230616.222945.430_clear_346+79_001_001_017_sci_coadd_Cat_1.fits
222635v8/LAST.01.08.03_20230616.222945.430_clear_346+79_001_001_016_sci_coadd_Cat_1.fits
222635v8/LAST.01.08.03_20230616.222955.434_clear_346+79_002_001_015_sci_coadd_Cat_1.fits
222635v8/LAST.01.08.03_20230616.222945.430_clear_346+79_002_001_014_sci_coadd_Cat_1.fits
222635v8/LAST.01.08.03_20230616.222955.434_clear_346+79_002_001_013_sci_coadd_Cat_1.fits
222635v8/LAST.01.08.03_20230616.222945.430_clear_346+79_002_001_012_sci_coadd_Cat_1.fits
222635v8/LAST.01.08.03_20230616.222945.430_clear_346+79_001_001_011_sci_coadd_Cat_1.fits
222635v8/LAST.01.08.03_20230616.222945.430_clear_346+79_002_001_010_sci_coadd_Cat_1.fits
222635v8/LAST.01.08.03_20230616.222945.430_clear_346+79_001_001_009_sci_coadd_Cat_1.fits
222635v8/LAST.01.08.03_20230616.222945.430_clear_346+79_001_001_008_sci_coadd_Cat_1.fits
222635v8/LAST.01.08.03_20230616.222945.430_clear_346+79_001_001_007_sci_coadd_Cat_1.fits
222635v8/LAST.01.08.03_20230616.222945.430_clear_346+79_001_001_006_sci_coadd_Cat_1.fits
222635v8/LAST.01.08.03_20230616.222945.430_clear_346+79_001_001_005_sci_coadd_Cat_1.fits
222635v8/LAST.01.08.03_20230616.222945.430_clear_346+79_001_001_004_sci_coadd_Cat_1.fits
222635v8/LAST.01.08.03_20230616.222945.430_clear_346+79_001_001_003_sci_coadd_Cat_1.fits
222635v8/LAST.01.08.03_20230616.222945.430_clear_346+79_001_001_002_sci_coadd_Cat_1.fits
222635v8/LAST.01.08.03_20230616.222945.430_clear_346+79_001_001_001_sci_coadd_Cat_1.fits

@EranOfek, should I change the corresponding line of imProc.stack.coadd 
from 
Result.HeaderData = replaceVal(Result.HeaderData, 'MIDJD', {median(MidJD)});
to, say:
Result.HeaderData = replaceVal(Result.HeaderData, 'MIDJD', {min(MidJD)});
?

**Comment by agioffe** [comment]
@EranOfek, let us return to this issue once again.

For now the dates in the headers of a Coadd stack may differ, e.g.:
K>> [JD1-JD1(1) MIDJD1-MIDJD1(1)]
ans =
   1.0e-03 *
                   0                   0
                   0                   0
                   0                   0
                   0                   0
                   0                   0
                   0                   0
                   0                   0
                   0                   0
                   0                   0
   0.231649726629257                   0
                   0                   0
   0.231649726629257                   0
   0.231649726629257   0.115785282105207
   0.231649726629257                   0
   0.231649726629257   0.115785282105207
                   0                   0
                   0                   0
   0.231649726629257                   0
   0.231649726629257                   0
   0.231649726629257   0.115785282105207
                   0                   0
                   0                   0
                   0                   0
                   0                   0
K>> 

and this leads to the following spread in the output file names:

sasha@WRX80:~/matlab/data/pipeline/LAST$ ls 2023/06/16/proc/222635v1/*coadd*Image*
2023/06/16/proc/222635v1/LAST.01.08.03_20230616.222945.430_clear_346+79_000_001_001_sci_coadd_Image_1.fits
2023/06/16/proc/222635v1/LAST.01.08.03_20230616.222945.430_clear_346+79_000_001_002_sci_coadd_Image_1.fits
2023/06/16/proc/222635v1/LAST.01.08.03_20230616.222945.430_clear_346+79_000_001_003_sci_coadd_Image_1.fits
2023/06/16/proc/222635v1/LAST.01.08.03_20230616.222945.430_clear_346+79_000_001_004_sci_coadd_Image_1.fits
2023/06/16/proc/222635v1/LAST.01.08.03_20230616.222945.430_clear_346+79_000_001_005_sci_coadd_Image_1.fits
2023/06/16/proc/222635v1/LAST.01.08.03_20230616.222945.430_clear_346+79_000_001_006_sci_coadd_Image_1.fits
2023/06/16/proc/222635v1/LAST.01.08.03_20230616.222945.430_clear_346+79_000_001_007_sci_coadd_Image_1.fits
2023/06/16/proc/222635v1/LAST.01.08.03_20230616.222945.430_clear_346+79_000_001_008_sci_coadd_Image_1.fits
2023/06/16/proc/222635v1/LAST.01.08.03_20230616.222945.430_clear_346+79_000_001_009_sci_coadd_Image_1.fits
2023/06/16/proc/222635v1/LAST.01.08.03_20230616.222945.430_clear_346+79_000_001_010_sci_coadd_Image_1.fits
2023/06/16/proc/222635v1/LAST.01.08.03_20230616.222945.430_clear_346+79_000_001_011_sci_coadd_Image_1.fits
2023/06/16/proc/222635v1/LAST.01.08.03_20230616.222945.430_clear_346+79_000_001_012_sci_coadd_Image_1.fits
2023/06/16/proc/222635v1/LAST.01.08.03_20230616.222945.430_clear_346+79_000_001_014_sci_coadd_Image_1.fits
2023/06/16/proc/222635v1/LAST.01.08.03_20230616.222945.430_clear_346+79_000_001_016_sci_coadd_Image_1.fits
2023/06/16/proc/222635v1/LAST.01.08.03_20230616.222945.430_clear_346+79_000_001_017_sci_coadd_Image_1.fits
2023/06/16/proc/222635v1/LAST.01.08.03_20230616.222945.430_clear_346+79_000_001_018_sci_coadd_Image_1.fits
2023/06/16/proc/222635v1/LAST.01.08.03_20230616.222945.430_clear_346+79_000_001_019_sci_coadd_Image_1.fits
2023/06/16/proc/222635v1/LAST.01.08.03_20230616.222945.430_clear_346+79_000_001_021_sci_coadd_Image_1.fits
2023/06/16/proc/222635v1/LAST.01.08.03_20230616.222945.430_clear_346+79_000_001_022_sci_coadd_Image_1.fits
2023/06/16/proc/222635v1/LAST.01.08.03_20230616.222945.430_clear_346+79_000_001_023_sci_coadd_Image_1.fits
2023/06/16/proc/222635v1/LAST.01.08.03_20230616.222945.430_clear_346+79_000_001_024_sci_coadd_Image_1.fits
2023/06/16/proc/222635v1/LAST.01.08.03_20230616.222955.434_clear_346+79_000_001_013_sci_coadd_Image_1.fits
2023/06/16/proc/222635v1/LAST.01.08.03_20230616.222955.434_clear_346+79_000_001_015_sci_coadd_Image_1.fits
2023/06/16/proc/222635v1/LAST.01.08.03_20230616.222955.434_clear_346+79_000_001_020_sci_coadd_Image_1.fits
sasha@WRX80:~/matlab/data/pipeline/LAST$ 

Here the fields 13, 15, and 20 differ from all the others according to the MIDJD keyword. 

So we are to decide, either to
1. Keep this as it is so that the user understand that in some fields some of the exposures were sorted out and this led to different time stamps of the coadded subimages. Then all the post-processing codes should be aware of such a possibility
or to
2. Standardize the time stamps by putting into all the MIDJD keywords of all the coadded subimages something like a pre-calculated value of 
MIDJD_RAW = median(julday(RawHeader))

What would you prefer?

**Comment by yossishv** [comment]
There are two issues here:
1. Filename - starttime vs. midtime
2. How midtime is calculated?

For (1) I have no strong opinion.
For (2), this should be weighted correctly. If for example a few images were rejected out of the coadd of the visit - the midtime should be calcualted and weighted correctly to represnt the effective mid time of the coadd image.

**Comment by agioffe** [comment]
As we discussed, I replaced the MIDJD midtime (that was a median) for a weighted mean:
sum(MidJD.*VecExpTime)/sum(VecExpTime)

But the first issue (file name time stamps non-uniform across the FOV) is not solved, because the FN takes the name from this keyword (MIDJD) which differs from subimage to subimage. We can leave it as it is and close the issue, but I tend to think that 
it would be more useful if the time stamp of the COADD file names is the same for the whole visit.

**Comment by agioffe** [comment]
I have standardized the COADD file names so that the time stamp therein corresponds to the JD of the first raw image in the visit. At the same time, the MIDJD keyword in each of the COADD files is a weighted mean of the MIDJDs of the PROC images which were actually used to build this particular COADD. As soon as my pull request is accepted, these changes are in _dev1_.
