### ISSUE TITLE
pipeline: failed on last01e at prepMasterFlat

### ISSUE THREAD

**Issue by PolishookDavid** [EranOfek/AstroPack#316]
>> D.prepMasterFlat
Error using  - 
Matrix dimensions must agree.
Error in AstroImage/funBinaryProp (line 2565)
                            Result(Ires).(Args.DataProp).(Args.DataPropIn) = Operator(Tmp1, Tmp2, Args.OpArgs{:});
Error in imProc.dark.debias (line 88)
    Result = funBinaryProp(ImObj(IsNotBias), Bias, @minus, 'OpArgs',{},...
Error in pipeline.DemonLAST/prepMasterFlat (line 1411)
                        AI = imProc.dark.debias(AI, Obj.CI.Bias, Args.debiasArgs{:});

**Comment by EranOfek** [comment]
The reason for this is that one of the images from which the flat was constructed had different size
[9576 x 6389] instead of [9600 x 6422] in all the other cases.
The reason for this is not clear.
For the time being I deleted the image.
It may be useful to write a function that check this automatically and remove such images.
