### ISSUE TITLE
Asteroid catalog matching doesn't work at negative declinations

### ISSUE THREAD

**Issue by RuslanKonno** [EranOfek/AstroPack#492]
I've found that during the transients detection, some asteroids are not properly matched despite being clearly within the search radius, this seems to occur when the transients/asteroid catalogs are in the south (negative declinations), likely this is some issue with the declination sorting for fast catalog matching.

The following zip file has a transients catalog and an asteroid catalog with this issue.
[cats.zip](https://github.com/user-attachments/files/16459777/cats.zip)

If I try to match them via

`imProc.match.match2solarSystem(TranCat, 'InCooUnits', 'deg','SourcesColDistName', 'N_DistMP', 'AstCat', AstCat_new,'JD', 2460521.47921127, 'AddMag2Obj', true,'ColMag', 'Mag', 'ObjColMag', 'N_MagMP','SearchRadius',20)`

there will be no match, even though I know there is one - asteroid 'Magnanimity'

However, if I flip the sign of the declination in both catalogs 

> AstCat_new.replaceCol(table(-AstCat_new.getCol('Dec')),'Dec')
> TranCat.replaceCol(-TranCat.getCol('Dec'),'Dec')

And try the exact same match, the asteroid is properly matched.

**Comment by EranOfek** [comment]
As far as I can tell, TranCat is not sorted by Declination.
The reason is that, from some reason, it contains complex numbers.
1. It will be good if you can identify when/where it happens and open an
additional/separate issue on this.
2. Meanwhile, I took:
```
TranCat.Catalog=abs(TranCat.Catalog);
TranCat.sortrows('Dec');
```
but this didn't help.
Next, I plotted:
```
plot(AstCat_new.Table.RA, AstCat_new.Table.Dec,'.');
hold on
plot(TranCat.Table.RA, TranCat.Table.Dec,'.');
```

but it seems that the two catalogs are not overlapping (maybe a sign
problem)
The TranCat is at positive Dec, while the AstCat is at negative Dec.
In order to debug this we need to understand how AstCat was produced, and
how the RA,Dec where calculated...

**Comment by RuslanKonno** [comment]
Some notes

On 1 - seems the aperture photometry is returning a complex error, I'll investigate and make an issue if need be.

On 2 - they're both at negative declinations but you flipped the sign of TranCat by using abs().

**Comment by RuslanKonno** [comment]
Saving the absolute value of the error in aperture photometry, i.e. as a real and not a complex number, leads to no more complex numbers in the catalog and the asteroid matching works. Since this isn't a catalog matching problem, I'll close this issue and perhaps open a new one for the photometry.
