### ISSUE TITLE
pipeline.DemonLAST/main clutter in function

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#538]
The main function became too complicated.
specifically: if Args.Insert2DB (line 3101 to 3170) need to be cleaned.
This block should be updated and replaced with a single (or a few lines).

**Comment by agioffe** [comment]
First, we are to decide whether we are going to use it at all or just insert to the DB via a separate process.
But anyway, I can take all the block out to some class function of **pipeline.DemonLAST** and keep just a couple of lines in **pipeline.DemonLAST.main**.

**Comment by agioffe** [comment]
I moved most of the DB operations to a separate class function **pipeline.DemonLAST.insert2DB** . 
I ran some tests with the unitTest data (1 real LAST visit), so I hope it will work smoothly enough.

**Comment by EranOfek** [comment]
I can't find: pipeline.DemonLAST.insert2DB

**Comment by agioffe** [comment]
Even after **git pull** ?
I pushed it from the office desktop and can see it on the laptop after **git pull**.

**Comment by EranOfek** [comment]
I don't understand?

**Comment by agioffe** [comment]
I mean that on Monday I changed the class file at the office desktop and did git push. I can see these changes on the laptop, so you should be able to see them too as far as you do git pull. 
What can you see when you do
> edit pipeline.DemonLAST.insert2DB ?

Doesn't it show you this separate function in pipeline.DemonLAST? Can you see that the DB part in pipeline.DemonLAST.main is now just several line instead of the clutter that was before?
