### ISSUE TITLE
transient detection failed + sucssful?

### ISSUE THREAD

**Issue by EranOfek** [EranOfek/AstroPack#542]
In this case:LAST.01.01.01_20241023.235042.709_clear_1397_007_001_001_sci_raw_Image_1.fits
I get - successful and failed???

14:02:17.355 [INF] last01e: pipeline.DemonLAST finished saving Merged Cats and Matched sources for group 4 / RunTime: 349.5
14:02:17.418 [INF] last01e: pipeline.DemonLAST finished saving Asteroid data for group 4 / RunTime: 349.5
14:02:17.430 [INF] last01e: pipeline.DemonLAST - Transients detection / group 4
14:03:06.353 [INF] last01e: pipeline.DemonLAST / Transients detection - Succesful exit, 0 transient(s) found.
14:03:07.208 [INF] last01e: pipeline.DemonLAST - Transients detection / Failed
14:03:07.212 [INF] last01e: pipeline.DemonLAST - Transients alerting / group 4
14:03:07.235 [INF] last01e: pipeline.DemonLAST / Transients alerting - No transients found.

**Comment by RuslanKonno** [comment]
This issue is two part

1. There's a file of transients candidates called TranDB.mat in the science directory that acts as a temporary database for transients. I recently updated the columns of the transient catalogs so they longer matched. I removed the old files so now they will be created with the new columns.
2. The transients detection was successful but the multi-epoch matching wasn't due to point 1. Both were done in the same try catch, which reported a failure due to the multi-epoch failure. This is confusing so I isolated the multi-epoch matching into its own try catch.

Problem should be fixed but feel free to re-open if it isn't.
